language: node_js
node_js:
  - "11"

sudo: required

cache: npm

notifications:
  - email: false

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
