language: node_js
node_js:
  - "11"

sudo: required

cache: npm

notifications:
  - email: false

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/
  on:
    branch: master
